import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../core/formatters.dart';
import '../models/dashboard_metrics.dart';
import '../models/expense.dart';
import '../models/product.dart';
import '../models/sale.dart';

class ReportService {
  Future<String> exportSalesCsv(List<SaleRecord> sales) async {
    final rows = <List<String>>[
      ['Invoice', 'Date', 'Payment Method', 'Subtotal', 'Discount', 'Total'],
      ...sales.map(
        (sale) => [
          sale.invoiceNo,
          sale.createdAt.toIso8601String(),
          sale.paymentMethod,
          sale.subtotal.toStringAsFixed(2),
          sale.discount.toStringAsFixed(2),
          sale.total.toStringAsFixed(2),
        ],
      ),
    ];

    final csv = rows.map((row) => row.map(_csvCell).join(',')).join('\r\n');
    final path = await _exportPath('sales', 'csv');
    await File(path).writeAsString('\ufeff$csv', encoding: utf8, flush: true);
    return path;
  }

  Future<String> exportInventoryCsv(List<Product> products) async {
    final rows = <List<String>>[
      [
        'Product',
        'SKU',
        'Barcode',
        'Category',
        'Cost Price',
        'Selling Price',
        'Stock',
        'Low Stock Level',
      ],
      ...products.map(
        (product) => [
          product.name,
          product.sku,
          product.barcode,
          product.category,
          product.costPrice.toStringAsFixed(2),
          product.sellingPrice.toStringAsFixed(2),
          product.stockQty.toStringAsFixed(2),
          product.lowStockLevel.toStringAsFixed(2),
        ],
      ),
    ];

    final csv = rows.map((row) => row.map(_csvCell).join(',')).join('\r\n');
    final path = await _exportPath('inventory', 'csv');
    await File(path).writeAsString('\ufeff$csv', encoding: utf8, flush: true);
    return path;
  }

  Future<Uint8List> buildSummaryPdf({
    required PdfPageFormat pageFormat,
    required String businessName,
    required DashboardMetrics metrics,
    required List<SaleRecord> sales,
    required List<Expense> expenses,
  }) async {
    final safeBusinessName = businessName.trim().isEmpty
        ? 'My Business'
        : businessName.trim();
    final format = _safePageFormat(pageFormat, PdfPageFormat.a4);
    final document = pw.Document(
      title: '$safeBusinessName Business Summary',
      author: 'Airmonlink Business Manager',
      creator: 'Airmonlink Business Manager',
      subject: 'Business performance summary',
    );
    final theme = pw.ThemeData.withFont(
      base: pw.Font.helvetica(),
      bold: pw.Font.helveticaBold(),
      italic: pw.Font.helveticaOblique(),
      boldItalic: pw.Font.helveticaBoldOblique(),
    );

    document.addPage(
      pw.MultiPage(
        pageFormat: format,
        theme: theme,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => pw.Container(
          padding: const pw.EdgeInsets.only(bottom: 12),
          decoration: const pw.BoxDecoration(
            border: pw.Border(
              bottom: pw.BorderSide(color: PdfColors.blueGrey300, width: 1),
            ),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Expanded(
                child: pw.Text(
                  safeBusinessName,
                  maxLines: 2,
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.blue900,
                  ),
                ),
              ),
              pw.SizedBox(width: 16),
              pw.Text(
                AppFormatters.date(DateTime.now()),
                style: const pw.TextStyle(fontSize: 10),
              ),
            ],
          ),
        ),
        footer: (context) => pw.Container(
          padding: const pw.EdgeInsets.only(top: 8),
          decoration: const pw.BoxDecoration(
            border: pw.Border(
              top: pw.BorderSide(color: PdfColors.blueGrey200, width: 0.5),
            ),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by Airmonlink Business Manager',
                style: const pw.TextStyle(
                  fontSize: 8,
                  color: PdfColors.grey700,
                ),
              ),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: const pw.TextStyle(
                  fontSize: 8,
                  color: PdfColors.grey700,
                ),
              ),
            ],
          ),
        ),
        build: (context) => [
          pw.SizedBox(height: 18),
          pw.Text(
            'Business Summary',
            style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 5),
          pw.Text(
            'A printable overview of current business performance and recent records.',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 18),
          pw.Wrap(
            spacing: 10,
            runSpacing: 10,
            children: [
              _metricBox('Today Sales', _pdfMoney(metrics.todaySales)),
              _metricBox('Today Transactions', '${metrics.todayTransactions}'),
              _metricBox(
                'Monthly Gross Profit',
                _pdfMoney(metrics.monthGrossProfit),
              ),
              _metricBox('Monthly Expenses', _pdfMoney(metrics.monthExpenses)),
              _metricBox('Customer Credit', _pdfMoney(metrics.customerDebt)),
              _metricBox('Products', '${metrics.totalProducts}'),
              _metricBox('Low Stock', '${metrics.lowStockProducts}'),
            ],
          ),
          pw.SizedBox(height: 24),
          _sectionTitle('Recent Sales'),
          pw.SizedBox(height: 8),
          if (sales.isEmpty)
            _emptySection('No sales have been recorded yet.')
          else
            pw.TableHelper.fromTextArray(
              headers: const ['Invoice', 'Date', 'Payment', 'Total'],
              data: sales.take(25).map((sale) {
                return [
                  sale.invoiceNo,
                  AppFormatters.dateTime(sale.createdAt),
                  sale.paymentMethod,
                  _pdfMoney(sale.total),
                ];
              }).toList(),
              headerDecoration: const pw.BoxDecoration(
                color: PdfColors.blueGrey100,
              ),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              cellStyle: const pw.TextStyle(fontSize: 9),
              border: pw.TableBorder.all(
                color: PdfColors.blueGrey200,
                width: 0.5,
              ),
              cellPadding: const pw.EdgeInsets.all(6),
            ),
          pw.SizedBox(height: 24),
          _sectionTitle('Recent Expenses'),
          pw.SizedBox(height: 8),
          if (expenses.isEmpty)
            _emptySection('No expenses have been recorded yet.')
          else
            pw.TableHelper.fromTextArray(
              headers: const ['Description', 'Category', 'Date', 'Amount'],
              data: expenses.take(25).map((expense) {
                return [
                  expense.title,
                  expense.category,
                  AppFormatters.dateTime(expense.createdAt),
                  _pdfMoney(expense.amount),
                ];
              }).toList(),
              headerDecoration: const pw.BoxDecoration(
                color: PdfColors.blueGrey100,
              ),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              cellStyle: const pw.TextStyle(fontSize: 9),
              border: pw.TableBorder.all(
                color: PdfColors.blueGrey200,
                width: 0.5,
              ),
              cellPadding: const pw.EdgeInsets.all(6),
            ),
        ],
      ),
    );

    return _validatedPdfBytes(await document.save(), 'business summary');
  }

  Future<Uint8List> buildReceiptPdf({
    required PdfPageFormat pageFormat,
    required String businessName,
    required String businessPhone,
    required String businessAddress,
    required String invoiceNo,
    required SaleDraft sale,
    required DateTime soldAt,
    String? customerName,
  }) async {
    final safeBusinessName = businessName.trim().isEmpty
        ? 'My Business'
        : businessName.trim();
    final receiptFormat = _safeReceiptFormat(pageFormat, sale.items.length);
    final document = pw.Document(
      title: 'Receipt $invoiceNo',
      author: 'Airmonlink Business Manager',
      creator: 'Airmonlink Business Manager',
      subject: 'Sales receipt',
    );
    final theme = pw.ThemeData.withFont(
      base: pw.Font.helvetica(),
      bold: pw.Font.helveticaBold(),
      italic: pw.Font.helveticaOblique(),
      boldItalic: pw.Font.helveticaBoldOblique(),
    );

    document.addPage(
      pw.MultiPage(
        pageFormat: receiptFormat,
        theme: theme,
        margin: pw.EdgeInsets.all(4 * PdfPageFormat.mm),
        build: (context) => [
          pw.Center(
            child: pw.Text(
              safeBusinessName,
              textAlign: pw.TextAlign.center,
              style: pw.TextStyle(fontSize: 15, fontWeight: pw.FontWeight.bold),
            ),
          ),
          if (businessAddress.trim().isNotEmpty) ...[
            pw.SizedBox(height: 3),
            pw.Center(
              child: pw.Text(
                businessAddress.trim(),
                textAlign: pw.TextAlign.center,
                style: const pw.TextStyle(fontSize: 8.5),
              ),
            ),
          ],
          if (businessPhone.trim().isNotEmpty) ...[
            pw.SizedBox(height: 2),
            pw.Center(
              child: pw.Text(
                businessPhone.trim(),
                style: const pw.TextStyle(fontSize: 8.5),
              ),
            ),
          ],
          pw.SizedBox(height: 8),
          _receiptRule(),
          pw.SizedBox(height: 6),
          _receiptDetail('Invoice', invoiceNo),
          _receiptDetail('Date', AppFormatters.dateTime(soldAt)),
          _receiptDetail('Payment', sale.paymentMethod),
          if (customerName?.trim().isNotEmpty == true)
            _receiptDetail('Customer', customerName!.trim()),
          pw.SizedBox(height: 6),
          _receiptRule(),
          pw.SizedBox(height: 6),
          ...sale.items.expand(
            (item) => [
              pw.Text(
                item.productName,
                style: pw.TextStyle(
                  fontSize: 9,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 2),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    '${_quantity(item.quantity)} x ${_pdfMoney(item.unitPrice)}',
                    style: const pw.TextStyle(fontSize: 8.5),
                  ),
                  pw.Text(
                    _pdfMoney(item.total),
                    style: const pw.TextStyle(fontSize: 8.5),
                  ),
                ],
              ),
              pw.SizedBox(height: 6),
            ],
          ),
          _receiptRule(),
          pw.SizedBox(height: 6),
          _receiptTotal('Subtotal', _pdfMoney(sale.subtotal)),
          if (sale.discount > 0)
            _receiptTotal('Discount', '-${_pdfMoney(sale.discount)}'),
          pw.SizedBox(height: 3),
          _receiptTotal('TOTAL', _pdfMoney(sale.total), emphasized: true),
          pw.SizedBox(height: 8),
          _receiptRule(),
          pw.SizedBox(height: 8),
          pw.Center(
            child: pw.Text(
              'Thank you for your business.',
              textAlign: pw.TextAlign.center,
              style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Center(
            child: pw.Text(
              'Generated by Airmonlink Business Manager',
              textAlign: pw.TextAlign.center,
              style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey700),
            ),
          ),
        ],
      ),
    );

    return _validatedPdfBytes(await document.save(), 'receipt');
  }

  Future<Uint8List> buildPrinterTestPdf({
    required PdfPageFormat pageFormat,
    required String businessName,
  }) async {
    final format = _safePageFormat(pageFormat, PdfPageFormat.a4);
    final document = pw.Document(
      title: 'Printer Test Page',
      author: 'Airmonlink Business Manager',
    );

    document.addPage(
      pw.Page(
        pageFormat: format,
        margin: const pw.EdgeInsets.all(36),
        build: (context) => pw.Container(
          decoration: pw.BoxDecoration(
            border: pw.Border.all(color: PdfColors.black, width: 2),
          ),
          padding: const pw.EdgeInsets.all(24),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'AIRMONLINK PRINTER TEST',
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 14),
              pw.Text(
                businessName.trim().isEmpty
                    ? 'My Business'
                    : businessName.trim(),
              ),
              pw.Text('Generated: ${AppFormatters.dateTime(DateTime.now())}'),
              pw.SizedBox(height: 20),
              pw.Text(
                'If you can read this text and see the border, the PDF and printer are rendering correctly.',
                style: const pw.TextStyle(fontSize: 13),
              ),
              pw.SizedBox(height: 24),
              pw.Container(height: 24, color: PdfColors.black),
              pw.SizedBox(height: 8),
              pw.Container(
                height: 24,
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.black, width: 1),
                ),
              ),
            ],
          ),
        ),
      ),
    );

    return _validatedPdfBytes(await document.save(), 'printer test page');
  }

  Future<String> exportSummaryPdf({
    required String businessName,
    required DashboardMetrics metrics,
    required List<SaleRecord> sales,
    required List<Expense> expenses,
  }) async {
    final bytes = await buildSummaryPdf(
      pageFormat: PdfPageFormat.a4,
      businessName: businessName,
      metrics: metrics,
      sales: sales,
      expenses: expenses,
    );
    final path = await _exportPath('business-summary', 'pdf');
    await File(path).writeAsBytes(bytes, flush: true);
    return path;
  }

  Future<String> exportReceiptPdf({
    required String businessName,
    required String businessPhone,
    required String businessAddress,
    required String invoiceNo,
    required SaleDraft sale,
    required DateTime soldAt,
    String? customerName,
  }) async {
    final bytes = await buildReceiptPdf(
      pageFormat: PdfPageFormat.roll80,
      businessName: businessName,
      businessPhone: businessPhone,
      businessAddress: businessAddress,
      invoiceNo: invoiceNo,
      sale: sale,
      soldAt: soldAt,
      customerName: customerName,
    );
    final safeInvoice = invoiceNo.replaceAll(RegExp(r'[^A-Za-z0-9_-]'), '-');
    final path = await _exportPath('receipt-$safeInvoice', 'pdf');
    await File(path).writeAsBytes(bytes, flush: true);
    return path;
  }

  static pw.Widget _sectionTitle(String value) {
    return pw.Text(
      value,
      style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
    );
  }

  static pw.Widget _emptySection(String message) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
      ),
      child: pw.Text(message, style: const pw.TextStyle(fontSize: 9)),
    );
  }

  static pw.Widget _metricBox(String label, String value) {
    return pw.Container(
      width: 160,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.blueGrey200),
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            label,
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 6),
          pw.Text(
            value,
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
        ],
      ),
    );
  }

  static pw.Widget _receiptRule() {
    return pw.Container(
      height: 0.7,
      width: double.infinity,
      color: PdfColors.black,
    );
  }

  static pw.Widget _receiptDetail(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 2),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 46,
            child: pw.Text(
              '$label:',
              style: pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.Expanded(
            child: pw.Text(value, style: const pw.TextStyle(fontSize: 8)),
          ),
        ],
      ),
    );
  }

  static pw.Widget _receiptTotal(
    String label,
    String value, {
    bool emphasized = false,
  }) {
    final style = pw.TextStyle(
      fontSize: emphasized ? 12 : 9,
      fontWeight: emphasized ? pw.FontWeight.bold : pw.FontWeight.normal,
    );
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 2),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: style),
          pw.Text(value, style: style),
        ],
      ),
    );
  }

  Future<String> _exportPath(String prefix, String extension) async {
    final documents = await getApplicationDocumentsDirectory();
    final directory = Directory(
      p.join(documents.path, 'Airmonlink Business Manager', 'Exports'),
    );
    await directory.create(recursive: true);
    final timestamp = DateTime.now()
        .toIso8601String()
        .replaceAll(':', '-')
        .replaceAll('.', '-');
    return p.join(directory.path, '$prefix-$timestamp.$extension');
  }

  static PdfPageFormat _safeReceiptFormat(
    PdfPageFormat requested,
    int itemCount,
  ) {
    final requestedWidth = requested.width.isFinite && requested.width > 0
        ? requested.width
        : PdfPageFormat.roll80.width;

    final width = requestedWidth <= 65 * PdfPageFormat.mm
        ? 57 * PdfPageFormat.mm
        : 80 * PdfPageFormat.mm;

    final estimatedHeight =
        (150 + itemCount.clamp(1, 100) * 16) * PdfPageFormat.mm;

    final height = estimatedHeight.clamp(
      180 * PdfPageFormat.mm,
      1000 * PdfPageFormat.mm,
    );

    return PdfPageFormat(width, height.toDouble());
  }

  static PdfPageFormat _safePageFormat(
    PdfPageFormat requested,
    PdfPageFormat fallback,
  ) {
    if (!requested.width.isFinite ||
        !requested.height.isFinite ||
        requested.width <= 0 ||
        requested.height <= 0) {
      return fallback;
    }
    return requested;
  }

  static Uint8List _validatedPdfBytes(Uint8List bytes, String documentName) {
    final header = bytes.length >= 5 ? String.fromCharCodes(bytes.take(5)) : '';
    if (bytes.length < 500 || header != '%PDF-') {
      throw StateError(
        'The $documentName PDF could not be generated correctly.',
      );
    }
    return bytes;
  }

  static String _csvCell(String value) {
    final safeValue = RegExp(r'^[=+\-@]').hasMatch(value) ? "'$value" : value;
    final escaped = safeValue.replaceAll('"', '""');
    return '"$escaped"';
  }

  static String _pdfMoney(num value) => 'GHS ${value.toStringAsFixed(2)}';

  static String _quantity(double value) {
    if (value == value.roundToDouble()) return value.toStringAsFixed(0);
    return value.toStringAsFixed(2);
  }
}
